@tool
class_name RoofConstants
extends RefCounted


const EVENT_EPS := 0.0005

const COINCIDENT_POINT_EPS := 1e-6

const FACE_WELD_EPS := 1e-4

const VELOCITY_MATCH_EPS := 1e-6

const COLLAPSE_SPEED_EPS := 1e-9

const SPLIT_APPROACH_EPS := 1e-9

const REFLEX_CROSS_EPS := 1e-6

const ANTIPARALLEL_DENOM_EPS := 1e-4

const ITERATION_CAP_QUADRATIC := 8
const ITERATION_CAP_BASE := 64


const MIN_POLYGON_AREA := 1e-4

const MIN_FACE_AREA := 1e-6

const AREA_TOLERANCE_ABS := 0.01
const AREA_TOLERANCE_REL := 0.001

const FLAT_PITCH_DEGREES := 0.05

const MAX_PITCH_DEGREES := 89.0

const WALL_CLEARANCE_MARGIN := 0.01


const WALL_CLIP_EMBED := 0.02

const MAX_HOLE_SPLIT_DEPTH := 8

const CLIP_SPLIT_PADDING := 1.0


const GABLE_MATCH_EPS := 0.01

const GABLE_APEX_OFFSET_EPS := 0.01

const GABLE_LINE_EPS := 1e-3


const GUTTER_FASCIA_GAP := 0.005

const GUTTER_TOP_DROP := 0.02

const GUTTER_THICKNESS := 0.012

const GUTTER_MIN_RUN_LENGTH := 0.3

const HALF_ROUND_SEGMENTS := 8

const DOWNSPOUT_MIN_SPACING_CELLS := 2.0

const DOWNSPOUT_SPAN_SPACING_FRACTION := 0.5

const DOWNSPOUT_MERGE_DISTANCE := 0.6

const DOWNSPOUT_WALL_EDGE_SLACK := 0.01

const DOWNSPOUT_ELBOW_GAP := 0.01

const DOWNSPOUT_WALL_GAP := 0.01

const DOWNSPOUT_FOOT_EMBED := 0.05

const DOWNSPOUT_WALL_REACH_EPS := 0.05

const DOWNSPOUT_SEARCH_STEP := 0.05

const DOWNSPOUT_GRID_SEARCH_CELLS := 3


const EAVE_OFFSET_EPS := 1e-3

const RIDGE_OFFSET_EPS := 1e-3

const EDGE_KEY_QUANTUM := 1e-4

const MIN_EDGE_LENGTH := 1e-4
